# API KEYS (PLACEHOLDERS ONLY - DO NOT USE REAL KEYS)
POLYMARKET_API_KEY = "PLACEHOLDER"
KALSHI_API_KEY = "PLACEHOLDER"
MANIFOLD_API_KEY = "PLACEHOLDER"
BETFAIR_API_KEY = "PLACEHOLDER"

# Scan settings
SCAN_INTERVAL_SECONDS = 2
MAX_CACHE_AGE_SECONDS = 10

# Rate limiting
MAX_REQUESTS_PER_MINUTE = 30

# Minimum thresholds
MIN_ARBITRAGE_PROFIT_PCT = 0.1  # 0.1% minimum to display
MIN_EV_PCT = 1.0  # 1% minimum EV to display

# Default stake for calculations
DEFAULT_STAKE_USD = 1000.0
